version: '3.8'
services:
  backend:
    image: tb3-backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - PORT=8080
  frontend:
    image: tb3-frontend
    ports:
      - "${FRONTEND_PORT}:8080"
    environment:
      - PORT=8080
